name: AxiosEconomie
version: '${version}'

main: fr.kilian.economy.Main
api-version: '26.3'
load: POSTWORLD

authors: [ TablePasDroite ]

depend:
  - AxiosAPI
commands:
  balance:
    description: Show your current balance

  pay:
    description: Send money to another player
    usage: /pay <player> <amount>

  bank:
    description: Manage your bank account
    usage: /bank [deposit|withdraw] [amount]
